---
# Default: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
default: true
MD003:
  style: atx
MD004:
  style: dash
MD013: false
MD035:
  style: ---
MDo43:
  match_case: true
MD044:
  names:
    - GitHub
    - github
MD046:
  style: fenced
MD048:
  style: backtick
MD049:
  style: underscore
MD050:
  style: asterisk
MD055:
  style: leading_and_trailing
